// File generated by the FlutterFire CLI (and hand-edited from the latest
// google-services.json / GoogleService-Info.plist after re-registering apps
// under com.boycearmory.investing).
//
// If you re-run `flutterfire configure --project=boyce-armory-investing`,
// this file will be rewritten. The values below should match.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate firebase_options.dart.',
        );
    }
  }

  // Web is not currently shipped. Placeholder values keep the file compiling;
  // runtime Firebase calls on web will fail until this block is populated.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    authDomain: 'REPLACE_ME.firebaseapp.com',
    storageBucket: 'REPLACE_ME.appspot.com',
  );

  // From google-services.json (com.boycearmory.investing).
  // NOTE: appId here is stale until you re-register the Android app in
  // Firebase Console under com.boycearmory.investing and update with the
  // new value (or re-run `flutterfire configure --project=boyce-armory-investing`).
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-5KUV3d1fgdZswFR_JfXdeu8fg9Ctrs',
    appId: '1:315573366149:android:9f709652e400e0e69da8ec',
    messagingSenderId: '315573366149',
    projectId: 'boyce-armory-investing',
    storageBucket: 'boyce-armory-investing.firebasestorage.app',
  );

  // From GoogleService-Info.plist (com.boycearmory.investing).
  // NOTE: appId here is stale until you re-register the iOS app in Firebase
  // Console under com.boycearmory.investing and update with the new value
  // (or re-run `flutterfire configure --project=boyce-armory-investing`).
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRtWOwgaZS5YYOMRRaD3tvs2MhPlvVODE',
    appId: '1:315573366149:ios:8112703f383878239da8ec',
    messagingSenderId: '315573366149',
    projectId: 'boyce-armory-investing',
    storageBucket: 'boyce-armory-investing.firebasestorage.app',
    iosBundleId: 'com.boycearmory.investing',
  );

  // macOS not shipped. Placeholder.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
    iosBundleId: 'com.boycearmory.investing',
  );
}
