// File generated by the FlutterFire CLI.
//
// REPLACE THIS FILE by running:
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=<your-firebase-project-id>
//
// The placeholders below let the project compile; runtime Firebase calls will
// fail until this file is regenerated with real values.

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run `flutterfire configure` to generate firebase_options.dart.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    authDomain: 'REPLACE_ME.firebaseapp.com',
    storageBucket: 'REPLACE_ME.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-5KUV3d1fgdZswFR_JfXdeu8fg9Ctrs',
    appId: '1:315573366149:android:f39edde6a8a8af079da8ec',
    messagingSenderId: '315573366149',
    projectId: 'boyce-armory-investing',
    storageBucket: 'boyce-armory-investing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRtWOwgaZS5YYOMRRaD3tvs2MhPlvVODE',
    appId: '1:315573366149:ios:cec8f17c7e1c8d6e9da8ec',
    messagingSenderId: '315573366149',
    projectId: 'boyce-armory-investing',
    storageBucket: 'boyce-armory-investing.firebasestorage.app',
    iosBundleId: 'com.example.boyceArmory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME.appspot.com',
    iosBundleId: 'com.boycearmory.boyce_armory',
  );
}