# Boyce Armory iOS Podfile.
#
# Required for Firebase native pods (firebase_core, firebase_messaging,
# cloud_firestore, firebase_auth, etc.) to link correctly. Without this file,
# Xcode can't resolve any of the FlutterFire plugins.
#
# After editing pubspec.yaml or this file, run:
#   cd app && flutter pub get && cd ios && pod install --repo-update
#
# If you bump Flutter or Firebase versions and pod install starts complaining
# about minimum iOS, raise the platform line below.

# Firebase iOS SDK requires iOS 13+.
platform :ios, '13.0'

# Silence CocoaPods analytics network calls during build.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    # Force iOS deployment target to 13.0 on all pods so transitive deps don't
    # downgrade us (some older pods default to 11.0 / 12.0 and break Firebase).
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
